<a href="https://colab.research.google.com/github/Tri-M/MACHINE-LEARNING/blob/master/DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Classification with Sigmoid Activation Function - Perceptron


In [3]:
import numpy as np

class PerceptronSigmoid:
    def __init__(self, input_dim, learning_rate=0.01, epochs=1000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = np.zeros(input_dim + 1)  # +1 for the bias term

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def predict(self, X):
        linear_output = np.dot(X, self.weights[1:]) + self.weights[0]
        return self.sigmoid(linear_output)

    def fit(self, X, y):
        for _ in range(self.epochs):
            predictions = self.predict(X)
            errors = y - predictions
            # Update weights using gradient descent
            self.weights[1:] += self.learning_rate * np.dot(X.T, errors * predictions * (1 - predictions)) / len(y)
            self.weights[0] += self.learning_rate * np.sum(errors * predictions * (1 - predictions)) / len(y)

# Example dataset (features and labels)
X = np.array([[2, 3], [1, 5], [2, 1], [4, 4]])
y = np.array([1, 1, 0, 0])  # Binary labels

# Train perceptron with sigmoid activation
perceptron = PerceptronSigmoid(input_dim=2)
perceptron.fit(X, y)

# Predictions
predictions = perceptron.predict(X)
print("Predictions:", predictions)


Predictions: [0.52260748 0.84023827 0.30241508 0.32459358]


Regression with Sigmoid Activation Function

In [4]:
class LogisticRegression:
    def __init__(self, input_dim, learning_rate=0.01, epochs=1000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = np.zeros(input_dim + 1)  # +1 for the bias term

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def predict(self, X):
        return self.sigmoid(np.dot(X, self.weights[1:]) + self.weights[0])

    def fit(self, X, y):
        for _ in range(self.epochs):
            predictions = self.predict(X)
            errors = y - predictions
            self.weights[1:] += self.learning_rate * np.dot(X.T, errors * predictions * (1 - predictions)) / len(y)
            self.weights[0] += self.learning_rate * np.sum(errors * predictions * (1 - predictions)) / len(y)

# Example dataset (features and target values)
X = np.array([[2, 3], [1, 5], [2, 1], [4, 4]])
y = np.array([0.7, 0.9, 0.5, 0.8])  # Continuous values between 0 and 1

# Train logistic regression model
model = LogisticRegression(input_dim=2)
model.fit(X, y)

# Predictions
predictions = model.predict(X)
print("Predictions:", predictions)


Predictions: [0.7239555  0.82483385 0.58901449 0.7865573 ]


Binary Clasification using Sigmoid

In [5]:
import numpy as np

class PerceptronSigmoid:
    def __init__(self, input_dim, learning_rate=0.01, epochs=1000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = np.zeros(input_dim + 1)  # +1 for the bias term

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def predict(self, X):
        linear_output = np.dot(X, self.weights[1:]) + self.weights[0]
        return self.sigmoid(linear_output)

    def fit(self, X, y):
        for _ in range(self.epochs):
            predictions = self.predict(X)
            errors = y - predictions
            # Update weights using gradient descent
            self.weights[1:] += self.learning_rate * np.dot(X.T, errors * predictions * (1 - predictions)) / len(y)
            self.weights[0] += self.learning_rate * np.sum(errors * predictions * (1 - predictions)) / len(y)

# Example dataset (features and binary labels)
X = np.array([[2, 3], [1, 5], [2, 1], [4, 4]])
y = np.array([1, 1, 0, 0])  # Binary labels

# Train perceptron with sigmoid activation
perceptron = PerceptronSigmoid(input_dim=2)
perceptron.fit(X, y)

# Predictions
predictions = perceptron.predict(X)
print("Predictions:", predictions)


Predictions: [0.52260748 0.84023827 0.30241508 0.32459358]


Multiway Classification using sigmoid

In [6]:
class SoftmaxClassifier:
    def __init__(self, input_dim, num_classes, learning_rate=0.01, epochs=1000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.num_classes = num_classes
        self.weights = np.zeros((input_dim + 1, num_classes))  # +1 for the bias term

    def softmax(self, x):
        e_x = np.exp(x - np.max(x, axis=1, keepdims=True))
        return e_x / np.sum(e_x, axis=1, keepdims=True)

    def predict(self, X):
        linear_output = np.dot(X, self.weights[1:]) + self.weights[0]
        return self.softmax(linear_output)

    def fit(self, X, y):
        y_one_hot = np.eye(self.num_classes)[y]  # Convert labels to one-hot encoding
        for _ in range(self.epochs):
            predictions = self.predict(X)
            errors = y_one_hot - predictions
            # Update weights using gradient descent
            self.weights[1:] += self.learning_rate * np.dot(X.T, errors) / len(y)
            self.weights[0] += self.learning_rate * np.sum(errors, axis=0) / len(y)

# Example dataset (features and multi-class labels)
X = np.array([[2, 3], [1, 5], [2, 1], [4, 4], [5, 2]])
y = np.array([0, 1, 1, 2, 2])  # Multi-class labels (0, 1, 2)

# Train softmax classifier
num_classes = 3
model = SoftmaxClassifier(input_dim=2, num_classes=num_classes)
model.fit(X, y)

# Predictions
predictions = model.predict(X)
print("Predictions (probabilities):", predictions)
print("Predicted class labels:", np.argmax(predictions, axis=1))


Predictions (probabilities): [[0.27858534 0.47170944 0.24970522]
 [0.25279805 0.71098736 0.03621459]
 [0.23183402 0.29949563 0.46867034]
 [0.14704844 0.17749676 0.6754548 ]
 [0.03282211 0.02385199 0.94332591]]
Predicted class labels: [1 1 2 2 2]


MLP classification

In [8]:
import numpy as np

class MLP:
    def __init__(self, input_dim, hidden_dim, output_dim, learning_rate=0.01, epochs=1000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.output_dim = output_dim

        # Initialize weights and biases
        self.W1 = np.random.randn(input_dim, hidden_dim) * 0.01
        self.b1 = np.zeros(hidden_dim)
        self.W2 = np.random.randn(hidden_dim, output_dim) * 0.01
        self.b2 = np.zeros(output_dim)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def forward(self, X):
        self.z1 = np.dot(X, self.W1) + self.b1
        self.a1 = self.sigmoid(self.z1)
        self.z2 = np.dot(self.a1, self.W2) + self.b2
        self.a2 = self.sigmoid(self.z2)
        return self.a2

    def compute_loss(self, y, a2):
        return np.mean(-y * np.log(a2 + 1e-8) - (1 - y) * np.log(1 - a2 + 1e-8))

    def backward(self, X, y):
        m = y.shape[0]

        # Reshape y to be (m, 1)
        y = y.reshape(-1, 1)

        # Compute gradients for W2, b2
        dz2 = self.a2 - y
        dW2 = np.dot(self.a1.T, dz2) / m
        db2 = np.sum(dz2, axis=0) / m

        # Compute gradients for W1, b1
        da1 = np.dot(dz2, self.W2.T)
        dz1 = da1 * self.sigmoid_derivative(self.a1)
        dW1 = np.dot(X.T, dz1) / m
        db1 = np.sum(dz1, axis=0) / m

        # Update weights and biases
        self.W1 -= self.learning_rate * dW1
        self.b1 -= self.learning_rate * db1
        self.W2 -= self.learning_rate * dW2
        self.b2 -= self.learning_rate * db2

    def fit(self, X, y):
        for _ in range(self.epochs):
            a2 = self.forward(X)
            loss = self.compute_loss(y, a2)
            self.backward(X, y)
            if _ % 100 == 0:
                print(f'Epoch {_}, Loss: {loss}')

    def predict(self, X):
        return self.forward(X)

# Example dataset (features and binary labels)
np.random.seed(42)
X = np.random.rand(100, 10)  # 100 samples, 10 features
y = np.random.randint(0, 2, 100)  # Binary labels

# Train MLP
mlp = MLP(input_dim=10, hidden_dim=5, output_dim=1, learning_rate=0.01, epochs=1000)
mlp.fit(X, y)

# Predictions
predictions = mlp.predict(X)
print("Predictions:", predictions)


Epoch 0, Loss: 0.6931783293600098
Epoch 100, Loss: 0.6926128260121536
Epoch 200, Loss: 0.6924314772416237
Epoch 300, Loss: 0.6923735225274599
Epoch 400, Loss: 0.692355128226725
Epoch 500, Loss: 0.6923493669584837
Epoch 600, Loss: 0.6923476087338131
Epoch 700, Loss: 0.6923471002715745
Epoch 800, Loss: 0.6923469708440018
Epoch 900, Loss: 0.6923469496615973
Predictions: [[0.4799591 ]
 [0.48000719]
 [0.47991922]
 [0.47989733]
 [0.47992911]
 [0.47989523]
 [0.47996447]
 [0.47991671]
 [0.47993646]
 [0.48000181]
 [0.47999933]
 [0.47997769]
 [0.47993663]
 [0.47995854]
 [0.47998023]
 [0.47994635]
 [0.47992962]
 [0.47999499]
 [0.47999998]
 [0.47999831]
 [0.47996931]
 [0.47996174]
 [0.47994651]
 [0.47991113]
 [0.47988388]
 [0.48000952]
 [0.47990862]
 [0.47994521]
 [0.47996503]
 [0.48002822]
 [0.47994783]
 [0.47993097]
 [0.47994877]
 [0.47998252]
 [0.47992836]
 [0.47991127]
 [0.47999852]
 [0.4799902 ]
 [0.47993428]
 [0.47988641]
 [0.47992602]
 [0.47996363]
 [0.47990122]
 [0.47994671]
 [0.47995712]


MLP Regression

In [9]:
import numpy as np

class MLPRegressor:
    def __init__(self, input_dim, hidden_dim, output_dim, learning_rate=0.01, epochs=1000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.output_dim = output_dim

        # Initialize weights and biases
        self.W1 = np.random.randn(input_dim, hidden_dim)
        self.b1 = np.zeros(hidden_dim)
        self.W2 = np.random.randn(hidden_dim, output_dim)
        self.b2 = np.zeros(output_dim)

    def relu(self, x):
        return np.maximum(0, x)

    def relu_derivative(self, x):
        return (x > 0).astype(float)

    def forward(self, X):
        self.z1 = np.dot(X, self.W1) + self.b1
        self.a1 = self.relu(self.z1)
        self.z2 = np.dot(self.a1, self.W2) + self.b2
        return self.z2

    def compute_loss(self, y, y_pred):
        return np.mean((y - y_pred) ** 2)

    def backward(self, X, y):
        m = y.shape[0]

        # Compute gradients for W2, b2
        dz2 = self.forward(X) - y
        dW2 = np.dot(self.a1.T, dz2) / m
        db2 = np.sum(dz2, axis=0) / m

        # Compute gradients for W1, b1
        da1 = np.dot(dz2, self.W2.T)
        dz1 = da1 * self.relu_derivative(self.z1)
        dW1 = np.dot(X.T, dz1) / m
        db1 = np.sum(dz1, axis=0) / m

        # Update weights and biases
        self.W1 -= self.learning_rate * dW1
        self.b1 -= self.learning_rate * db1
        self.W2 -= self.learning_rate * dW2
        self.b2 -= self.learning_rate * db2

    def fit(self, X, y):
        for _ in range(self.epochs):
            y_pred = self.forward(X)
            loss = self.compute_loss(y, y_pred)
            self.backward(X, y)
            if _ % 100 == 0:
                print(f'Epoch {_}, Loss: {loss}')

    def predict(self, X):
        return self.forward(X)

# Example dataset (features and target values)
np.random.seed(42)
X = np.random.rand(100, 10)  # 100 samples, 10 features
y = np.random.rand(100, 1)   # Continuous target values

# Train MLP
mlp_reg = MLPRegressor(input_dim=10, hidden_dim=5, output_dim=1, learning_rate=0.01, epochs=1000)
mlp_reg.fit(X, y)

# Predictions
predictions = mlp_reg.predict(X)
print("Predictions:", predictions)


Epoch 0, Loss: 10.869375306356314
Epoch 100, Loss: 0.18900485819725074
Epoch 200, Loss: 0.12452007460522566
Epoch 300, Loss: 0.11235214249940041
Epoch 400, Loss: 0.10829604917250438
Epoch 500, Loss: 0.1060272104536896
Epoch 600, Loss: 0.1043683115715168
Epoch 700, Loss: 0.10302721098598173
Epoch 800, Loss: 0.10189833917470714
Epoch 900, Loss: 0.10092803868688298
Predictions: [[0.45013343]
 [0.37824011]
 [0.53866085]
 [0.68261682]
 [0.55700662]
 [0.51186834]
 [0.32081977]
 [0.7005094 ]
 [0.62238406]
 [0.46001217]
 [0.53368965]
 [0.60571267]
 [0.61916271]
 [0.47860233]
 [0.40989641]
 [0.58748714]
 [0.34937402]
 [0.49121772]
 [0.56205557]
 [0.53462785]
 [0.43219494]
 [0.52569841]
 [0.53462082]
 [0.45986811]
 [0.69829178]
 [0.50856415]
 [0.76733824]
 [0.61119015]
 [0.45175996]
 [0.39052283]
 [0.60175882]
 [0.62344811]
 [0.666314  ]
 [0.52998785]
 [0.44766833]
 [0.50789685]
 [0.68625701]
 [0.47434851]
 [0.49831631]
 [0.69457091]
 [0.55243476]
 [0.44842768]
 [0.65281693]
 [0.531202  ]
 [0.75

Ridge and lasso regularization

In [10]:
import math

class RegularizedLinearRegression:
    def __init__(self, input_dim, learning_rate=0.01, epochs=1000, alpha=1.0, regularization_type='ridge'):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.alpha = alpha  # Regularization strength
        self.regularization_type = regularization_type  # 'ridge' or 'lasso'
        self.weights = [0] * (input_dim + 1)  # +1 for the bias term

    def predict(self, X):
        predictions = []
        for x in X:
            # Manual dot product and bias addition
            linear_output = sum(x[i] * self.weights[i + 1] for i in range(len(x))) + self.weights[0]
            predictions.append(linear_output)
        return predictions

    def fit(self, X, y):
        m = len(y)
        for _ in range(self.epochs):
            predictions = self.predict(X)
            errors = [y[i] - predictions[i] for i in range(m)]

            # Compute gradients
            gradient_weights = [0] * (len(X[0]) + 1)
            for i in range(m):
                for j in range(len(X[i])):
                    gradient_weights[j + 1] -= X[i][j] * errors[i] / m
                gradient_weights[0] -= errors[i] / m

            # Add regularization term
            if self.regularization_type == 'ridge':
                # Ridge: L2 regularization
                gradient_weights = [gradient_weights[i] + self.alpha * self.weights[i] for i in range(len(self.weights))]
            elif self.regularization_type == 'lasso':
                # Lasso: L1 regularization
                for i in range(1, len(gradient_weights)):
                    if self.weights[i] > 0:
                        gradient_weights[i] += self.alpha
                    elif self.weights[i] < 0:
                        gradient_weights[i] -= self.alpha

            # Update weights
            self.weights = [self.weights[i] - self.learning_rate * gradient_weights[i] for i in range(len(self.weights))]

# Example dataset (features and labels)
X = [[2, 3], [1, 5], [2, 1], [4, 4]]
y = [3, 7, 4, 8]  # Continuous target values

# Train Ridge Regression
ridge = RegularizedLinearRegression(input_dim=2, learning_rate=0.01, epochs=1000, alpha=1.0, regularization_type='ridge')
ridge.fit(X, y)
ridge_predictions = ridge.predict(X)
print("Ridge Predictions:", ridge_predictions)

# Train Lasso Regression
lasso = RegularizedLinearRegression(input_dim=2, learning_rate=0.01, epochs=1000, alpha=1.0, regularization_type='lasso')
lasso.fit(X, y)
lasso_predictions = lasso.predict(X)
print("Lasso Predictions:", lasso_predictions)


Ridge Predictions: [4.762276094336812, 6.004043884709963, 2.779029338522865, 7.236857403125375]
Lasso Predictions: [5.126457872210956, 6.377133825793503, 3.6611441897563224, 6.2883901711824475]


Multiway classification -  softmax regression

In [11]:
import numpy as np

class SoftmaxRegression:
    def __init__(self, input_dim, num_classes, learning_rate=0.01, epochs=1000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.num_classes = num_classes
        self.weights = np.zeros((input_dim + 1, num_classes))  # +1 for the bias term

    def softmax(self, z):
        exp_scores = np.exp(z - np.max(z, axis=1, keepdims=True))  # Numerical stability
        return exp_scores / np.sum(exp_scores, axis=1, keepdims=True)

    def cross_entropy_loss(self, y_true, y_pred):
        m = y_true.shape[0]
        correct_log_probs = -np.log(y_pred[range(m), y_true])
        loss = np.sum(correct_log_probs) / m
        return loss

    def predict(self, X):
        X_bias = np.hstack([np.ones((X.shape[0], 1)), X])  # Add bias term
        scores = np.dot(X_bias, self.weights)
        probabilities = self.softmax(scores)
        return probabilities

    def fit(self, X, y):
        X_bias = np.hstack([np.ones((X.shape[0], 1)), X])  # Add bias term

        for _ in range(self.epochs):
            # Forward pass
            scores = np.dot(X_bias, self.weights)
            probabilities = self.softmax(scores)

            # Compute loss
            loss = self.cross_entropy_loss(y, probabilities)

            # Backward pass
            m = X.shape[0]
            one_hot_y = np.zeros_like(probabilities)
            one_hot_y[range(m), y] = 1

            d_scores = (probabilities - one_hot_y) / m
            d_weights = np.dot(X_bias.T, d_scores)

            # Update weights
            self.weights -= self.learning_rate * d_weights

            # Print loss every 100 epochs
            if _ % 100 == 0:
                print(f'Epoch {_}: Loss {loss}')

# Example dataset (features and labels)
X = np.array([[2, 3], [1, 5], [2, 1], [4, 4]])
y = np.array([0, 1, 0, 1])  # Binary labels for two classes (0 and 1)

# Number of features and classes
input_dim = X.shape[1]
num_classes = 2

# Train Softmax Regression
softmax = SoftmaxRegression(input_dim=input_dim, num_classes=num_classes, learning_rate=0.01, epochs=1000)
softmax.fit(X, y)

# Predictions
probabilities = softmax.predict(X)
predictions = np.argmax(probabilities, axis=1)
print("Predictions:", predictions)


Epoch 0: Loss 0.6931471805599453
Epoch 100: Loss 0.5669266564736731
Epoch 200: Loss 0.5268147897183293
Epoch 300: Loss 0.5008922857365606
Epoch 400: Loss 0.48050862507147307
Epoch 500: Loss 0.46295849985488147
Epoch 600: Loss 0.4472085535950009
Epoch 700: Loss 0.43279128727862043
Epoch 800: Loss 0.41945867547817195
Epoch 900: Loss 0.4070574787560733
Predictions: [1 1 0 1]


Time permit auto encoding

In [12]:
import numpy as np

class Autoencoder:
    def __init__(self, input_dim, hidden_dim, learning_rate=0.01, epochs=1000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim

        # Initialize weights and biases
        self.W_enc = np.random.randn(input_dim, hidden_dim) * 0.1
        self.b_enc = np.zeros(hidden_dim)
        self.W_dec = np.random.randn(hidden_dim, input_dim) * 0.1
        self.b_dec = np.zeros(input_dim)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def forward(self, X):
        self.encoded = self.sigmoid(np.dot(X, self.W_enc) + self.b_enc)
        self.decoded = self.sigmoid(np.dot(self.encoded, self.W_dec) + self.b_dec)
        return self.decoded

    def fit(self, X):
        for _ in range(self.epochs):
            # Forward pass
            self.forward(X)

            # Compute the loss (mean squared error)
            loss = np.mean((X - self.decoded) ** 2)

            # Compute gradients for weights and biases
            error = X - self.decoded
            d_decoded = error * self.sigmoid_derivative(self.decoded)
            d_encoded = np.dot(d_decoded, self.W_dec.T) * self.sigmoid_derivative(self.encoded)

            # Update weights and biases
            self.W_dec += self.learning_rate * np.dot(self.encoded.T, d_decoded) / X.shape[0]
            self.b_dec += self.learning_rate * np.mean(d_decoded, axis=0)
            self.W_enc += self.learning_rate * np.dot(X.T, d_encoded) / X.shape[0]
            self.b_enc += self.learning_rate * np.mean(d_encoded, axis=0)

            if _ % 100 == 0:
                print(f'Epoch {_}: Loss {loss}')

    def encode(self, X):
        return self.sigmoid(np.dot(X, self.W_enc) + self.b_enc)

    def decode(self, encoded):
        return self.sigmoid(np.dot(encoded, self.W_dec) + self.b_dec)

# Example dataset (features)
X = np.array([[2, 3], [1, 5], [2, 1], [4, 4]])

# Create and train the autoencoder
autoencoder = Autoencoder(input_dim=2, hidden_dim=2, learning_rate=0.01, epochs=1000)
autoencoder.fit(X)

# Encode and decode the data
encoded = autoencoder.encode(X)
decoded = autoencoder.decode(encoded)

print("Original Data:\n", X)
print("Encoded Data:\n", encoded)
print("Decoded Data:\n", decoded)


Epoch 0: Loss 6.931339025919378
Epoch 100: Loss 5.949756949920452
Epoch 200: Loss 5.483716249523798
Epoch 300: Loss 5.304285697080962
Epoch 400: Loss 5.217841787659971
Epoch 500: Loss 5.168358332611501
Epoch 600: Loss 5.136675474391282
Epoch 700: Loss 5.114783014511559
Epoch 800: Loss 5.098805362778081
Epoch 900: Loss 5.086657096256903
Original Data:
 [[2 3]
 [1 5]
 [2 1]
 [4 4]]
Encoded Data:
 [[0.9450075  0.93305885]
 [0.9658088  0.96937958]
 [0.85709123 0.81155749]
 [0.98881173 0.98073883]]
Decoded Data:
 [[0.9686813  0.98210731]
 [0.97054643 0.98335729]
 [0.9607166  0.97668075]
 [0.97168271 0.98407116]]
